### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by mmintel** [spree-contrib/spree_i18n#587]
Hi there!

I got a missing translation on checkout/address and tried to fix it without success.

This is the message on the frontend:
```HTML
<span class="translation_missing" title="translation missing: de.spree.adjustment_labels.tax_rates.excluding_tax">Excluding Tax</span>
```

And this is how my de.yml looks like:
```YAML
de:
  hello: "Hello world"
  spree:
    adjustment_labels:
      tax_rates:
        excluding_tax: "Exklusive Steuer"
```

But this doesn't fix the error message.. other translations in that de.yml are working.. 

What's wrong with my fix?

**Comment by tvdeyen** [comment]
@mamhoff do you have any clue?

**Comment by mamhoff** [comment]
Can you post your `Gemfile.lock` so we know which Spree version you're at? Also, that particular label is actually one that should display the actual rate using `I18n`s string interpolation: 

```
en:
  spree:
    adjustment_labels:
      tax_rates:
        including_tax: '%{name}%{amount} (Included in Price)'
        excluding_tax: '%{name}%{amount}'
```

Might it be that it's actually some kind of `NameError`?
